### ISSUE TITLE
Helm chart support

### ISSUE THREAD

**Issue by alessio-perugini** [nats-nui/nui#10]
It would be cool to have a helm chart to easily deploy it in a k8s cluster.

If this is in your interest I could also take care of it. :nerd_face:

**Comment by pricelessrabbit** [comment]
yep it would be great to have it, my plan was to have a separate repo with chart releaser for that but then other stuff takes higher priority 😸. i'll try to have a look at it this week

**Comment by pricelessrabbit** [comment]
@alessio-perugini with "a bit" of delay, i added a basic setup to deploy NUI on k8s. you can find the repo [here](https://github.com/nats-nui/k8s). Feel free to contribute and improve it or tell me if you see some hotspots

**Comment by alessio-perugini** [comment]
@pricelessrabbit Sorry for replying so late but I was lazing around and didn't have a K8S cluster within reach. I've tried the helm chart, I like it. For my needs is more than enough. My use case is a local cluster created with kind as a dev-environment.
