### ISSUE TITLE
Support for root ca certificate and cert chain with nats auth options

### ISSUE THREAD

**Issue by anvy2** [nats-nui/nui#13]
Thanks for making this. Have been looking for something like this quite a while. Asking for support of root ca certificate while adding auth. The nats server I have is configured with certificates i have generated so doesn't work without giving root ca.

This could be added on cluster level too since a single cluster will have a single certificate for tls which can be used for auth.

It can also be further extended with client key and client cert. All of these options can be optional as the nats server can be connection with just root ca too if configured and optionally with providing the cert chain (client key, client cert) if required.

I would be happy to try adding the feature if you are accepting contributions.

**Comment by priolo** [comment]
Thank you so much for your feedback and for suggesting these improvements.
We truly appreciate your interest in contributing to the project.
At the moment, our team is on vacation,
so we will not be able to review or discuss the topic in detail for the next two weeks.
However, we will definitely look into your suggestions as soon as we get back.

**Comment by pricelessrabbit** [comment]
@anvy2 [release 0.4.3](https://github.com/nats-nui/nui/releases/tag/v0.4.3) adds support for client tls auth and ca, so i'm going to close this one. feel free to comment if you find out some issues 🐰
