### ISSUE TITLE
KVENTRY DETAIL window does not immediately show JSON values in a bucket 

### ISSUE THREAD

**Issue by dremekie** [nats-nui/nui#14]
First, NUI is a very useful UI for NATS. Very nice work.

I have KV entries that are all JSON encoded. When I select one of those entries in the KVENTRIES window, the window that shows the value is empty (even though there is a value present). However, when I click the COPY menu item, the actual stored value is successfully copied to the clipboard (I can paste it and see the correct value).

When I change the FORMAT to TEXT from the FORMAT selector, the same problem is seen.

To see the actual value in the window, I have to change the FORMAT to `hex` or `base64` first, and then change it back to `json` or `text`.

**Comment by priolo** [comment]
thanks for the feedback!
The UI was a bit of a challenge.
Initially we feared it would be too complicated compared to something classic.
I'll take a look at this issue soon.
I will keep you updated.
HI

**Comment by pricelessrabbit** [comment]
I also tried to reproduce the issue without success.
@dremekie could you provide additional details about that? which version of NUI are you using? is deskop app or docker setup?

**Comment by dremekie** [comment]
@pricelessrabbit It's the desktop version. The about popup does not show a version number. However, for the past few days, I have not seen any issues. I'll close this for now and re-open if I see it happening again.
