### ISSUE TITLE
Add possible edit consumer configuration in jetstream

### ISSUE THREAD

**Issue by klayders** [nats-nui/nui#2]
Hi, I didn`t see change consumer config in jetstream. Add this feature please!

**Comment by pricelessrabbit** [comment]
we can consider to add support for editing config of consumers in UI. Could i ask you your specifc use cases where you need to edit consumers config directly? do you also create new consumers manuallly or just edit the config of existent ones?

**Comment by klayders** [comment]
Specifically, I need to adjust the message offset in the consumer to enable re-reading of messages

**Comment by tema-mazy** [comment]
Please also add the possibility to add new / remove consumers like the command line client. thank you

**Comment by pricelessrabbit** [comment]
[v0.3.0](https://github.com/nats-nui/nui/releases/tag/v0.3.0) adds support to create and edit consumer configuration (and also to delete existing consumers). Let me know if you find some bugs opening another issue.
