### ISSUE TITLE
Unreadable characters

### ISSUE THREAD

**Issue by MikiEremiki** [nats-nui/nui#21]
One of the languages I use is Russian. 
Messages with these characters are displayed incorrectly.

![image](https://github.com/user-attachments/assets/1830983e-9408-4aec-ab74-4cb2a25fd27e)

It would be great if this could be fixed.

**Comment by pricelessrabbit** [comment]
@priolo looks like that also in core messages, sending russian chars is not working. can you have a look?

**Comment by priolo** [comment]
I don't know if it's related to this
the `btoa` transformation to `base64` doesn't work with non-latin characters
anyway you just need to encode everything and it should work
