### ISSUE TITLE
Auth using User/Password not working

### ISSUE THREAD

**Issue by AngeloBestetti** [nats-nui/nui#3]
Auth using User/Password not working, it does not connect.

**Comment by pricelessrabbit** [comment]
Just checked on bot web and desktop app and i got the connection using user and pass.
When you add the auth option, do you check the checkbox to enable it?

![image](https://github.com/nats-nui/nui/assets/22039194/4c844ea6-2ba3-43ce-ab91-e04f8d40d195)

**Comment by AngeloBestetti** [comment]
Yes, it´s checked

**Comment by AngeloBestetti** [comment]
![image](https://github.com/nats-nui/nui/assets/4291962/3a3205d1-1a28-4a4a-9c94-0b02937fe613)

**Comment by pricelessrabbit** [comment]
just released [v0.2.1](https://github.com/nats-nui/nui/releases/tag/v0.2.1) with connection status  in "logs" card, hoping that it will tell you the nats error behind the issue.


![image](https://github.com/nats-nui/nui/assets/22039194/36e5ff2d-803d-4abd-801d-f27913b9e6af).


Also, looks like from your screen that you add the connetion name but not the host 🐰 

Could you have a try with the new version and filling also the hosts field with your NATS host? Pls note that if you are running it from docker container, the host must be accessible from the container itself.

**Comment by AngeloBestetti** [comment]
I´m really sorry, was my mistake, I was just informing the "name" of the connection, as you can see in the snapshot the servers are empty, updated to 0.21 and filled all the fields and works. thank you again and sorry
