### ISSUE TITLE
SECURITY: nats-nui Docker image currently runs as root

### ISSUE THREAD

**Issue by vweckerle** [nats-nui/nui#36]
By default, the nats-nui Docker image ghcr.io/nats-nui/nui runs as root.
This is a possible security concern. I would suggest to switch to a non-privileged default user.

Current behaviour:
```
$ docker run --rm -it --entrypoint /bin/sh ghcr.io/nats-nui/nui:latest
/ # whoami
root
```

There are already a lot of non-root accounts in the image, why not use one of them?
```
$ cat /etc/passwd
root:x:0:0:root:/root:/bin/sh
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
```

**Comment by rud** [comment]
@vweckerle I think a PR would be welcome?

**Comment by pricelessrabbit** [comment]
is (in the NUI specific case) a real security issue to use the root account inside the container?
afaik the 2 main risks are related to escalate privileges on the host if you control the NUI container and a possible "hack" that can alter the NUI app or install malicious software inside the container itself, don't know if this apply to the NUI use case considering that the container should be deployed in local or protected environments. Also NATS server containers currently use root users to run the server.

**Comment by vweckerle** [comment]
The main issue here is that it is considered bad practice to run anything as root, unless absolutely necessary.
Therefore, many Kubernetes cluster administrators are disallowing this by default.
This means that the NATS NUI Docker image as you build it now is not usable for many people.

A simple example PR: https://github.com/nats-nui/nui/pull/40

**Comment by pricelessrabbit** [comment]
@vweckerle thanks for the feedback. So, I'm aware that this is not a perfect solution and does not solve automatically the cases in which you are forced to run the container as non root user in K8S. Unfortunately, there is no easy solution to update permissions / ownership of db volume in running instances, and starting as  `nui` user results in breaking all the existing instances of NUI. So the plan is to:
- deploy a version that starts as root and updates db ownership to the new user
- in a future version remove the root entrypoint and start the container directly as nui user.

About K8S best practices, for now is always possible to start the pod / container as NUI user explicitly with a security context setting `runAsUser: 1001`. In that case (given that the db ownership is manually updated) it should work as expected. Is this an acceptable solution?
