### ISSUE TITLE
base64 encoding problems

### ISSUE THREAD

**Issue by Idzanaagi** [nats-nui/nui#41]
Protobuf message comes to stream in base64 encoding. If you take it from NUI v0.4.4, everything is successfully decoded using an online tool. If taken from v0.5.0, the same message is not decoded. It should be noted that although it is the same message, it is displayed differently in different versions of the client.

**Comment by pricelessrabbit** [comment]
So which are the steps to reproduce?:
1
  - send a binary of a protobuf message
  - see it in NUI selecting `base64` view mode
  - decode the base64
  
or 2
- you send protobuf already converted in base64 to the stream / subject
- NUI does not show you a different base64 string

Is probably related to the changes of #28

**Comment by Idzanaagi** [comment]
first option

**Comment by pricelessrabbit** [comment]
[a3554e2](https://github.com/nats-nui/nui/commit/a3554e2ec6728e950b69e95e9bca060b12dbc8a1) fixed this. i'm going to release the semver within the next week. In the meantime if you need it you can use the [edge tag](https://github.com/nats-nui/nui/pkgs/container/nui/324242573?tag=edge) 🐰

**Comment by pricelessrabbit** [comment]
fixed in [v0.5.1](https://github.com/nats-nui/nui/releases/tag/v0.5.1)
