### ISSUE TITLE
compile for webkit2gtk-4.1 on Linux

### ISSUE THREAD

**Issue by akhenakh** [nats-nui/nui#9]
Arch is using webkit2gtk-4.1 

To compile nui I had to update `go.mod` to: 
`github.com/wailsapp/wails/v2 v2.9.1`

Use wails 2.9.1 and pass: `wails-2.9.1 build -tags webkit2_41`

Hoping it may help other users.

**Comment by pricelessrabbit** [comment]
thanks for the tip! i'll definitely have a look at that. Need to have some tries to ensure it not affects distros with `webkit2gtk-4.0`

**Comment by pricelessrabbit** [comment]
@akhenakh in  [v0.4.2-beta3](https://github.com/nats-nui/nui/releases/tag/v0.4.2-beta3 ) i added different builds to support both gtk 4.0 and 4.1.
Could you have a try with [linux-amd64-nui-app](https://github.com/nats-nui/nui/releases/download/v0.4.2-beta3/linux-amd64-nui-app)? it should work out of the box using using webkit2gtk-4.1

**Comment by pricelessrabbit** [comment]
released [v0.4.2](https://github.com/nats-nui/nui/releases/tag/v0.4.2) with default supprt for webkit2gtk-4.1

**Comment by akhenakh** [comment]
sorry for the late answer @pricelessrabbit  tested main branch successfully, thank you
